// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK-hI3KNpsecXtDy9nLpgjN235gOoDKXs',
    appId: '1:438823579389:web:d6dc928706665de9661894',
    messagingSenderId: '438823579389',
    projectId: 'academics-91250',
    authDomain: 'academics-91250.firebaseapp.com',
    storageBucket: 'academics-91250.firebasestorage.app',
    measurementId: 'G-N6SKK48CX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqW5bD_YGdr3g4AyaXhZ8vs75aNuvFyLM',
    appId: '1:438823579389:android:5848a3247b410112661894',
    messagingSenderId: '438823579389',
    projectId: 'academics-91250',
    storageBucket: 'academics-91250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTf7e7euUyJ8ne6HtEmm5HhIqYLgh5E1w',
    appId: '1:438823579389:ios:abcc715f95a21444661894',
    messagingSenderId: '438823579389',
    projectId: 'academics-91250',
    storageBucket: 'academics-91250.firebasestorage.app',
    iosClientId: '438823579389-1u5odlvhiov1bl7c6gjhrhknlinj9lom.apps.googleusercontent.com',
    iosBundleId: 'com.example.mfmcfAcademics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTf7e7euUyJ8ne6HtEmm5HhIqYLgh5E1w',
    appId: '1:438823579389:ios:abcc715f95a21444661894',
    messagingSenderId: '438823579389',
    projectId: 'academics-91250',
    storageBucket: 'academics-91250.firebasestorage.app',
    iosClientId: '438823579389-1u5odlvhiov1bl7c6gjhrhknlinj9lom.apps.googleusercontent.com',
    iosBundleId: 'com.example.mfmcfAcademics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK-hI3KNpsecXtDy9nLpgjN235gOoDKXs',
    appId: '1:438823579389:web:93d311c57ed1f460661894',
    messagingSenderId: '438823579389',
    projectId: 'academics-91250',
    authDomain: 'academics-91250.firebaseapp.com',
    storageBucket: 'academics-91250.firebasestorage.app',
    measurementId: 'G-NK5VG9VRVL',
  );
}
